# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0798a9b68153ecc342dbf23d76c95619235b125f1522b30f87e66c15e5847599cd19562e02a1aab2be4128d3c518526b2897bc075227f8abd8da22dc59e67073

test:
  secret_key_base: bce5469f89d4a270bc3c0c2737b2f888d91af1bdf3a7e5d5e173707fb897ba17b6afeec16f3f0642209edc222b00fedb928c72a0de4b175321df7c33ffb65f5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
